/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "/Users/shunshun/Github/blogs/docs/.vuepress/theme/node_modules/@vuepress/core/lib/client/root-mixins/updateMeta.js"
import m1 from "/Users/shunshun/Github/blogs/docs/.vuepress/theme/node_modules/@vuepress/plugin-nprogress/clientRootMixin.js"

export default [
  m0,
  m1
]