/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/shunshun/Github/blogs/docs/.vuepress/theme/layouts/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-53202c77",
    path: "/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-53202c77").then(next)
    },
  },
  {
    name: "v-014831c3",
    path: "/1970/01/01/mooc/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-014831c3").then(next)
    },
  },
  {
    path: "/1970/01/01/mooc/index.html",
    redirect: "/1970/01/01/mooc/"
  },
  {
    path: "/posts/InterView/mooc.html",
    redirect: "/1970/01/01/mooc/"
  },
  {
    name: "v-7fa8b2a4",
    path: "/1970/01/01/mac%E4%B8%8B%E9%85%8D%E7%BD%AEngxin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-7fa8b2a4").then(next)
    },
  },
  {
    path: "/1970/01/01/mac下配置ngxin/",
    redirect: "/1970/01/01/mac%E4%B8%8B%E9%85%8D%E7%BD%AEngxin/"
  },
  {
    path: "/1970/01/01/mac%E4%B8%8B%E9%85%8D%E7%BD%AEngxin/index.html",
    redirect: "/1970/01/01/mac%E4%B8%8B%E9%85%8D%E7%BD%AEngxin/"
  },
  {
    path: "/posts/Nginx/mac下配置ngxin.html",
    redirect: "/1970/01/01/mac%E4%B8%8B%E9%85%8D%E7%BD%AEngxin/"
  },
  {
    name: "v-70ef1ac0",
    path: "/2018/01/13/sequelize%E7%9A%84%E9%85%8D%E7%BD%AE/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-70ef1ac0").then(next)
    },
  },
  {
    path: "/2018/01/13/sequelize的配置/",
    redirect: "/2018/01/13/sequelize%E7%9A%84%E9%85%8D%E7%BD%AE/"
  },
  {
    path: "/2018/01/13/sequelize%E7%9A%84%E9%85%8D%E7%BD%AE/index.html",
    redirect: "/2018/01/13/sequelize%E7%9A%84%E9%85%8D%E7%BD%AE/"
  },
  {
    path: "/posts/Nodejs/Sequelize的配置.html",
    redirect: "/2018/01/13/sequelize%E7%9A%84%E9%85%8D%E7%BD%AE/"
  },
  {
    name: "v-adf3dafc",
    path: "/1970/01/01/%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-adf3dafc").then(next)
    },
  },
  {
    path: "/1970/01/01/常见面试题/",
    redirect: "/1970/01/01/%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98/"
  },
  {
    path: "/1970/01/01/%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98/index.html",
    redirect: "/1970/01/01/%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98/"
  },
  {
    path: "/posts/InterView/常见面试题.html",
    redirect: "/1970/01/01/%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98/"
  },
  {
    name: "v-22e1ddf0",
    path: "/2018/01/13/terminal%E4%B8%8B%E7%9A%84%E4%B8%80%E4%BA%9B%E9%85%8D%E7%BD%AE/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-22e1ddf0").then(next)
    },
  },
  {
    path: "/2018/01/13/terminal下的一些配置/",
    redirect: "/2018/01/13/terminal%E4%B8%8B%E7%9A%84%E4%B8%80%E4%BA%9B%E9%85%8D%E7%BD%AE/"
  },
  {
    path: "/2018/01/13/terminal%E4%B8%8B%E7%9A%84%E4%B8%80%E4%BA%9B%E9%85%8D%E7%BD%AE/index.html",
    redirect: "/2018/01/13/terminal%E4%B8%8B%E7%9A%84%E4%B8%80%E4%BA%9B%E9%85%8D%E7%BD%AE/"
  },
  {
    path: "/posts/Terminal/Terminal下的一些配置.html",
    redirect: "/2018/01/13/terminal%E4%B8%8B%E7%9A%84%E4%B8%80%E4%BA%9B%E9%85%8D%E7%BD%AE/"
  },
  {
    name: "v-4f2dd40f",
    path: "/1970/01/01/%E8%A7%A3%E5%86%B3%E4%BD%BF%E7%94%A8git-ssh%E6%AF%8F%E6%AC%A1%E9%83%BD%E8%A6%81%E8%BE%93%E5%85%A5%E5%AF%86%E7%A0%81/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-4f2dd40f").then(next)
    },
  },
  {
    path: "/1970/01/01/解决使用git-ssh每次都要输入密码/",
    redirect: "/1970/01/01/%E8%A7%A3%E5%86%B3%E4%BD%BF%E7%94%A8git-ssh%E6%AF%8F%E6%AC%A1%E9%83%BD%E8%A6%81%E8%BE%93%E5%85%A5%E5%AF%86%E7%A0%81/"
  },
  {
    path: "/1970/01/01/%E8%A7%A3%E5%86%B3%E4%BD%BF%E7%94%A8git-ssh%E6%AF%8F%E6%AC%A1%E9%83%BD%E8%A6%81%E8%BE%93%E5%85%A5%E5%AF%86%E7%A0%81/index.html",
    redirect: "/1970/01/01/%E8%A7%A3%E5%86%B3%E4%BD%BF%E7%94%A8git-ssh%E6%AF%8F%E6%AC%A1%E9%83%BD%E8%A6%81%E8%BE%93%E5%85%A5%E5%AF%86%E7%A0%81/"
  },
  {
    path: "/posts/Terminal/解决使用git，ssh每次都要输入密码.html",
    redirect: "/1970/01/01/%E8%A7%A3%E5%86%B3%E4%BD%BF%E7%94%A8git-ssh%E6%AF%8F%E6%AC%A1%E9%83%BD%E8%A6%81%E8%BE%93%E5%85%A5%E5%AF%86%E7%A0%81/"
  },
  {
    name: "v-73ee917a",
    path: "/1970/01/01/npm%E4%B8%8Eyarn/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-73ee917a").then(next)
    },
  },
  {
    path: "/1970/01/01/npm与yarn/",
    redirect: "/1970/01/01/npm%E4%B8%8Eyarn/"
  },
  {
    path: "/1970/01/01/npm%E4%B8%8Eyarn/index.html",
    redirect: "/1970/01/01/npm%E4%B8%8Eyarn/"
  },
  {
    path: "/posts/Nodejs/npm与yarn.html",
    redirect: "/1970/01/01/npm%E4%B8%8Eyarn/"
  },
  {
    name: "v-7ac8ca15",
    path: "/2018/01/13/axios%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-7ac8ca15").then(next)
    },
  },
  {
    path: "/2018/01/13/axios基础配置/",
    redirect: "/2018/01/13/axios%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE/"
  },
  {
    path: "/2018/01/13/axios%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE/index.html",
    redirect: "/2018/01/13/axios%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE/"
  },
  {
    path: "/posts/Vue/Axios基础配置.html",
    redirect: "/2018/01/13/axios%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE/"
  },
  {
    name: "v-8485141e",
    path: "/1970/01/01/autohotkey/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-8485141e").then(next)
    },
  },
  {
    path: "/1970/01/01/autohotkey/index.html",
    redirect: "/1970/01/01/autohotkey/"
  },
  {
    path: "/posts/Windows/autohotkey.html",
    redirect: "/1970/01/01/autohotkey/"
  },
  {
    name: "v-441fe432",
    path: "/1970/01/01/vuepress%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-441fe432").then(next)
    },
  },
  {
    path: "/1970/01/01/vuepress主题配置/",
    redirect: "/1970/01/01/vuepress%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE/"
  },
  {
    path: "/1970/01/01/vuepress%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE/index.html",
    redirect: "/1970/01/01/vuepress%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE/"
  },
  {
    path: "/posts/Vue/vuepress主题配置.html",
    redirect: "/1970/01/01/vuepress%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE/"
  },
  {
    name: "v-301842a5",
    path: "/1970/01/01/layout/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-301842a5").then(next)
    },
  },
  {
    path: "/1970/01/01/layout/index.html",
    redirect: "/1970/01/01/layout/"
  },
  {
    path: "/posts/Vue/layout.html",
    redirect: "/1970/01/01/layout/"
  },
  {
    name: "v-df6dc312",
    path: "/2019/03/13/leetcode/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-df6dc312").then(next)
    },
  },
  {
    path: "/2019/03/13/leetcode/index.html",
    redirect: "/2019/03/13/leetcode/"
  },
  {
    path: "/posts/leetcode/LeetCode.html",
    redirect: "/2019/03/13/leetcode/"
  },
  {
    name: "v-13758977",
    path: "/2018/11/07/frontmatter-in-vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-13758977").then(next)
    },
  },
  {
    path: "/2018/11/07/frontmatter-in-vuepress/index.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress/"
  },
  {
    path: "/posts/test/2018-11-7-frontmatter-in-vuepress.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress/"
  },
  {
    name: "v-3890e6a6",
    path: "/2018/11/07/frontmatter-in-vuepress-2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-3890e6a6").then(next)
    },
  },
  {
    path: "/2018/11/07/frontmatter-in-vuepress-2/index.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress-2/"
  },
  {
    path: "/posts/test/2018-11-7-frontmatter-in-vuepress-2.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress-2/"
  },
  {
    name: "v-a0c5d8de",
    path: "/2019/02/26/markdown-slot-2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-a0c5d8de").then(next)
    },
  },
  {
    path: "/2019/02/26/markdown-slot-2/index.html",
    redirect: "/2019/02/26/markdown-slot-2/"
  },
  {
    path: "/posts/test/2019-2-26-markdown-slot-2.html",
    redirect: "/2019/02/26/markdown-slot-2/"
  },
  {
    name: "v-32ba8faa",
    path: "/2018/11/07/frontmatter-in-vuepress-3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-32ba8faa").then(next)
    },
  },
  {
    path: "/2018/11/07/frontmatter-in-vuepress-3/index.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress-3/"
  },
  {
    path: "/posts/test/2018-11-7-frontmatter-in-vuepress-3.html",
    redirect: "/2018/11/07/frontmatter-in-vuepress-3/"
  },
  {
    name: "v-6ac979cf",
    path: "/2019/02/26/markdown-slot-3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-6ac979cf").then(next)
    },
  },
  {
    path: "/2019/02/26/markdown-slot-3/index.html",
    redirect: "/2019/02/26/markdown-slot-3/"
  },
  {
    path: "/posts/test/2019-2-26-markdown-slot-3.html",
    redirect: "/2019/02/26/markdown-slot-3/"
  },
  {
    name: "v-25f5e00d",
    path: "/2019/02/26/markdown-slot-4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-25f5e00d").then(next)
    },
  },
  {
    path: "/2019/02/26/markdown-slot-4/index.html",
    redirect: "/2019/02/26/markdown-slot-4/"
  },
  {
    path: "/posts/test/2019-2-26-markdown-slot-4.html",
    redirect: "/2019/02/26/markdown-slot-4/"
  },
  {
    name: "v-6f96281b",
    path: "/2019/02/26/markdown-slot/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-6f96281b").then(next)
    },
  },
  {
    path: "/2019/02/26/markdown-slot/index.html",
    redirect: "/2019/02/26/markdown-slot/"
  },
  {
    path: "/posts/test/2019-2-26-markdown-slot.html",
    redirect: "/2019/02/26/markdown-slot/"
  },
  {
    name: "v-1c1e25b7",
    path: "/1970/01/01/protype/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-1c1e25b7").then(next)
    },
  },
  {
    path: "/1970/01/01/protype/index.html",
    redirect: "/1970/01/01/protype/"
  },
  {
    path: "/posts/protype.html",
    redirect: "/1970/01/01/protype/"
  },
  {
    name: "v-6c8dcfe1",
    path: "/2019/05/06/writing-a-vuepress-theme-3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-6c8dcfe1").then(next)
    },
  },
  {
    path: "/2019/05/06/writing-a-vuepress-theme-3/index.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-3/"
  },
  {
    path: "/posts/test/2019-5-6-writing-a-vuepress-theme-3.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-3/"
  },
  {
    name: "v-69a2a463",
    path: "/2019/05/06/writing-a-vuepress-theme-2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-69a2a463").then(next)
    },
  },
  {
    path: "/2019/05/06/writing-a-vuepress-theme-2/index.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-2/"
  },
  {
    path: "/posts/test/2019-5-6-writing-a-vuepress-theme-2.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-2/"
  },
  {
    name: "v-6f78fb5f",
    path: "/2019/05/06/writing-a-vuepress-theme-4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-6f78fb5f").then(next)
    },
  },
  {
    path: "/2019/05/06/writing-a-vuepress-theme-4/index.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-4/"
  },
  {
    path: "/posts/test/2019-5-6-writing-a-vuepress-theme-4.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme-4/"
  },
  {
    name: "v-453ee96d",
    path: "/2019/05/06/writing-a-vuepress-theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-453ee96d").then(next)
    },
  },
  {
    path: "/2019/05/06/writing-a-vuepress-theme/index.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme/"
  },
  {
    path: "/posts/test/2019-5-6-writing-a-vuepress-theme.html",
    redirect: "/2019/05/06/writing-a-vuepress-theme/"
  },
  {
    name: "v-42d9971c",
    path: "/list/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("List", "v-42d9971c").then(next)
    },
    meta: {"pid":"post","id":"post"}
  },
  {
    path: "/list/index.html",
    redirect: "/list/"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Timeline", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-6d753ed6",
    path: "/tag/ngxin/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-6d753ed6").then(next)
    },
    meta: {"pid":"tags","id":"ngxin"}
  },
  {
    path: "/tag/ngxin/index.html",
    redirect: "/tag/ngxin/"
  },
  {
    name: "v-325022ec",
    path: "/tag/Mac/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-325022ec").then(next)
    },
    meta: {"pid":"tags","id":"Mac"}
  },
  {
    path: "/tag/Mac/index.html",
    redirect: "/tag/Mac/"
  },
  {
    name: "v-32518bc8",
    path: "/tag/Koa/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-32518bc8").then(next)
    },
    meta: {"pid":"tags","id":"Koa"}
  },
  {
    path: "/tag/Koa/index.html",
    redirect: "/tag/Koa/"
  },
  {
    name: "v-c955477c",
    path: "/tag/Sequelize/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-c955477c").then(next)
    },
    meta: {"pid":"tags","id":"Sequelize"}
  },
  {
    path: "/tag/Sequelize/index.html",
    redirect: "/tag/Sequelize/"
  },
  {
    name: "v-7a5f6990",
    path: "/tag/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-7a5f6990").then(next)
    },
    meta: {"pid":"tags","id":"JavaScript"}
  },
  {
    path: "/tag/JavaScript/index.html",
    redirect: "/tag/JavaScript/"
  },
  {
    name: "v-19493022",
    path: "/tag/面试题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-19493022").then(next)
    },
    meta: {"pid":"tags","id":"面试题"}
  },
  {
    path: "/tag/面试题/index.html",
    redirect: "/tag/面试题/"
  },
  {
    name: "v-32383f72",
    path: "/tag/git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-32383f72").then(next)
    },
    meta: {"pid":"tags","id":"git"}
  },
  {
    path: "/tag/git/index.html",
    redirect: "/tag/git/"
  },
  {
    name: "v-3231af64",
    path: "/tag/npm/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-3231af64").then(next)
    },
    meta: {"pid":"tags","id":"npm"}
  },
  {
    path: "/tag/npm/index.html",
    redirect: "/tag/npm/"
  },
  {
    name: "v-12dba5fe",
    path: "/tag/yarn/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-12dba5fe").then(next)
    },
    meta: {"pid":"tags","id":"yarn"}
  },
  {
    path: "/tag/yarn/index.html",
    redirect: "/tag/yarn/"
  },
  {
    name: "v-32475d9a",
    path: "/tag/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-32475d9a").then(next)
    },
    meta: {"pid":"tags","id":"Vue"}
  },
  {
    path: "/tag/Vue/index.html",
    redirect: "/tag/Vue/"
  },
  {
    name: "v-7d6421c3",
    path: "/tag/Axios/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-7d6421c3").then(next)
    },
    meta: {"pid":"tags","id":"Axios"}
  },
  {
    path: "/tag/Axios/index.html",
    redirect: "/tag/Axios/"
  },
  {
    name: "v-dea8ba54",
    path: "/tag/Windows/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-dea8ba54").then(next)
    },
    meta: {"pid":"tags","id":"Windows"}
  },
  {
    path: "/tag/Windows/index.html",
    redirect: "/tag/Windows/"
  },
  {
    name: "v-ded21334",
    path: "/tag/MacOS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-ded21334").then(next)
    },
    meta: {"pid":"tags","id":"MacOS"}
  },
  {
    path: "/tag/MacOS/index.html",
    redirect: "/tag/MacOS/"
  },
  {
    name: "v-dfb71430",
    path: "/tag/vuepress/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-dfb71430").then(next)
    },
    meta: {"pid":"tags","id":"vuepress"}
  },
  {
    path: "/tag/vuepress/index.html",
    redirect: "/tag/vuepress/"
  },
  {
    name: "v-3ae5b494",
    path: "/tag/markdown/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-3ae5b494").then(next)
    },
    meta: {"pid":"tags","id":"markdown"}
  },
  {
    path: "/tag/markdown/index.html",
    redirect: "/tag/markdown/"
  },
  {
    name: "v-3259a754",
    path: "/tag/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-3259a754").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/index.html",
    redirect: "/tag/CSS/"
  },
  {
    name: "v-89abd2d6",
    path: "/tag/算法/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-89abd2d6").then(next)
    },
    meta: {"pid":"tags","id":"算法"}
  },
  {
    path: "/tag/算法/index.html",
    redirect: "/tag/算法/"
  },
  {
    name: "v-79ce5560",
    path: "/tag/LeetCode/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-79ce5560").then(next)
    },
    meta: {"pid":"tags","id":"LeetCode"}
  },
  {
    path: "/tag/LeetCode/index.html",
    redirect: "/tag/LeetCode/"
  },
  {
    name: "v-f8241222",
    path: "/tag/frontmatter/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-f8241222").then(next)
    },
    meta: {"pid":"tags","id":"frontmatter"}
  },
  {
    path: "/tag/frontmatter/index.html",
    redirect: "/tag/frontmatter/"
  },
  {
    name: "v-e8d86dc8",
    path: "/tag/js/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-e8d86dc8").then(next)
    },
    meta: {"pid":"tags","id":"js"}
  },
  {
    path: "/tag/js/index.html",
    redirect: "/tag/js/"
  },
  {
    name: "v-58f012a0",
    path: "/tag/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-58f012a0").then(next)
    },
    meta: {"pid":"tags","id":"theme"}
  },
  {
    path: "/tag/theme/index.html",
    redirect: "/tag/theme/"
  },
  {
    name: "v-1559f73a",
    path: "/tag/blog/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterPagination", "v-1559f73a").then(next)
    },
    meta: {"pid":"tags","id":"blog"}
  },
  {
    path: "/tag/blog/index.html",
    redirect: "/tag/blog/"
  },
  {
    name: "v-f58cf1be",
    path: "/list/page/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f58cf1be").then(next)
    },
    meta: {"pid":"post","id":"post"}
  },
  {
    path: "/list/page/2/index.html",
    redirect: "/list/page/2/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]