/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "记录",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "About Me",
      "frontmatter": {},
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-53202c77",
      "path": "/about.html",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "v-show和 v-if 区别",
      "frontmatter": {
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/InterView/mooc.html",
      "relativePath": "posts/InterView/mooc.md",
      "key": "v-014831c3",
      "path": "/1970/01/01/mooc/",
      "headers": [
        {
          "level": 3,
          "title": "v-show和 v-if 区别",
          "slug": "v-show和-v-if-区别"
        },
        {
          "level": 3,
          "title": "为何 v-for中要有key",
          "slug": "为何-v-for中要有key"
        },
        {
          "level": 3,
          "title": "描述vue组件生命周期(有父子组件情况)",
          "slug": "描述vue组件生命周期-有父子组件情况"
        },
        {
          "level": 3,
          "title": "vue组件如何通讯",
          "slug": "vue组件如何通讯"
        },
        {
          "level": 3,
          "title": "描述组件渲染和更新过程",
          "slug": "描述组件渲染和更新过程"
        },
        {
          "level": 3,
          "title": "双向数据绑定和 v-model的实现原理",
          "slug": "双向数据绑定和-v-model的实现原理"
        },
        {
          "level": 3,
          "title": "vue 渲染过程",
          "slug": "vue-渲染过程"
        },
        {
          "level": 3,
          "title": "react 组件如何通讯",
          "slug": "react-组件如何通讯"
        },
        {
          "level": 3,
          "title": "jsx本质是什么",
          "slug": "jsx本质是什么"
        },
        {
          "level": 3,
          "title": "context是什么，有什么用途",
          "slug": "context是什么-有什么用途"
        },
        {
          "level": 3,
          "title": "shouldComponentUpdate 的用途",
          "slug": "shouldcomponentupdate-的用途"
        },
        {
          "level": 3,
          "title": "描述redux 单项数据流",
          "slug": "描述redux-单项数据流"
        },
        {
          "level": 3,
          "title": "setStete 是同步还是异步",
          "slug": "setstete-是同步还是异步"
        },
        {
          "level": 3,
          "title": "基于react/vue设计一个todolist(组件结构，redux state数据结构)",
          "slug": "基于react-vue设计一个todolist-组件结构-redux-state数据结构"
        },
        {
          "level": 3,
          "title": "前端代码为何要构建打包",
          "slug": "前端代码为何要构建打包"
        },
        {
          "level": 3,
          "title": "module chunk bundle分别是什么意思，有何区别",
          "slug": "module-chunk-bundle分别是什么意思-有何区别"
        },
        {
          "level": 3,
          "title": "一句话总结：",
          "slug": "一句话总结"
        },
        {
          "level": 3,
          "title": "loader和plugin 区别",
          "slug": "loader和plugin-区别"
        },
        {
          "level": 3,
          "title": "webpack如何实现懒加载",
          "slug": "webpack如何实现懒加载"
        },
        {
          "level": 3,
          "title": "webpack 常见性能优化",
          "slug": "webpack-常见性能优化"
        },
        {
          "level": 3,
          "title": "babel-runtime 和 babel-polyfill区别",
          "slug": "babel-runtime-和-babel-polyfill区别"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "Mac下配置ngxin",
      "frontmatter": {
        "title": "Mac下配置ngxin",
        "tags": [
          "ngxin",
          "Mac"
        ],
        "category": [
          "Mac",
          "ngxin"
        ],
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/Nginx/mac%E4%B8%8B%E9%85%8D%E7%BD%AEngxin.html",
      "relativePath": "posts/Nginx/mac下配置ngxin.md",
      "key": "v-7fa8b2a4",
      "path": "/1970/01/01/mac%E4%B8%8B%E9%85%8D%E7%BD%AEngxin/",
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "Nodejs ORM Sequelize 的基础配置",
      "frontmatter": {
        "title": "Nodejs ORM Sequelize 的基础配置",
        "date": "2018-01-13T16:07:32.000Z",
        "tags": [
          "Koa",
          "Sequelize"
        ],
        "category": "Nodejs",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/Nodejs/Sequelize%E7%9A%84%E9%85%8D%E7%BD%AE.html",
      "relativePath": "posts/Nodejs/Sequelize的配置.md",
      "key": "v-70ef1ac0",
      "path": "/2018/01/13/sequelize%E7%9A%84%E9%85%8D%E7%BD%AE/",
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "javascript题目",
      "frontmatter": {
        "title": "javascript题目",
        "tags": [
          "JavaScript",
          "面试题"
        ],
        "category": "前端",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/InterView/%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98.html",
      "relativePath": "posts/InterView/常见面试题.md",
      "key": "v-adf3dafc",
      "path": "/1970/01/01/%E5%B8%B8%E8%A7%81%E9%9D%A2%E8%AF%95%E9%A2%98/",
      "headers": [
        {
          "level": 2,
          "title": "HTML",
          "slug": "html"
        },
        {
          "level": 3,
          "title": "的 title 和 alt 有什么区别？",
          "slug": "的-title-和-alt-有什么区别"
        },
        {
          "level": 3,
          "title": "什么是 web 语义化？html5 有哪些语义化标签？语义化有什么好处？",
          "slug": "什么是-web-语义化-html5-有哪些语义化标签-语义化有什么好处"
        },
        {
          "level": 2,
          "title": "CSS",
          "slug": "css"
        },
        {
          "level": 3,
          "title": "display: none;与 visibility: hidden;的区别？",
          "slug": "display-none-与-visibility-hidden-的区别"
        },
        {
          "level": 3,
          "title": "如何分别水平、垂直居中一个元素？",
          "slug": "如何分别水平、垂直居中一个元素"
        },
        {
          "level": 2,
          "title": "JS",
          "slug": "js"
        },
        {
          "level": 3,
          "title": "如何实现一个 JS 对象的深度克隆？",
          "slug": "如何实现一个-js-对象的深度克隆"
        },
        {
          "level": 3,
          "title": "事件冒泡",
          "slug": "事件冒泡"
        },
        {
          "level": 3,
          "title": "在浏览器地址栏中输入一个 URL 后回车，背后会进行哪些技术步骤？",
          "slug": "在浏览器地址栏中输入一个-url-后回车-背后会进行哪些技术步骤"
        },
        {
          "level": 3,
          "title": "编程实现获取 URL 中的参数：",
          "slug": "编程实现获取-url-中的参数"
        },
        {
          "level": 3,
          "title": "输入习题",
          "slug": "输入习题"
        },
        {
          "level": 3,
          "title": "如何判断一个对象是否为函数？",
          "slug": "如何判断一个对象是否为函数"
        },
        {
          "level": 3,
          "title": "写出几种 js 跳转的常见方式？",
          "slug": "写出几种-js-跳转的常见方式"
        },
        {
          "level": 3,
          "title": "写出客户端存储 localStorage 和 sessionStorage 的 set、get 方法，localStorage 和 sessionStorage 有何区别？",
          "slug": "写出客户端存储-localstorage-和-sessionstorage-的-set、get-方法-localstorage-和-sessionstorage-有何区别"
        },
        {
          "level": 3,
          "title": "通过 JS 获取页面尺寸、屏幕的方法？",
          "slug": "通过-js-获取页面尺寸、屏幕的方法"
        },
        {
          "level": 3,
          "title": "列举 JS 实现跨域的几种方式？",
          "slug": "列举-js-实现跨域的几种方式"
        },
        {
          "level": 3,
          "title": "列举几种立即执行函数的实现方式。",
          "slug": "列举几种立即执行函数的实现方式。"
        },
        {
          "level": 3,
          "title": "var numberArray = [3, 6, 2, 4, 1, 5];",
          "slug": "var-numberarray-3-6-2-4-1-5"
        },
        {
          "level": 3,
          "title": "编写一个方法，去掉一个数组的重复元素",
          "slug": "编写一个方法-去掉一个数组的重复元素"
        },
        {
          "level": 3,
          "title": "写一个简单的 ajax 示例",
          "slug": "写一个简单的-ajax-示例"
        },
        {
          "level": 3,
          "title": "JavaScript 有哪些方法定义对象？",
          "slug": "javascript-有哪些方法定义对象"
        },
        {
          "level": 2,
          "title": "HTTP",
          "slug": "http"
        },
        {
          "level": 3,
          "title": "HTTP request 报文结构是怎样的？",
          "slug": "http-request-报文结构是怎样的"
        },
        {
          "level": 3,
          "title": "描述常见的 HTTP 状态码和 HTTP 方法",
          "slug": "描述常见的-http-状态码和-http-方法"
        },
        {
          "level": 3,
          "title": "HTTP 状态码及其含义？",
          "slug": "http-状态码及其含义"
        },
        {
          "level": 2,
          "title": "Vue",
          "slug": "vue"
        },
        {
          "level": 3,
          "title": "请简单描述 Vue 双向绑定底层实现原理，常用到的指令及 Vue 实例的生命周期",
          "slug": "请简单描述-vue-双向绑定底层实现原理-常用到的指令及-vue-实例的生命周期"
        },
        {
          "level": 2,
          "title": "算法题",
          "slug": "算法题"
        },
        {
          "level": 3,
          "title": "给出两个单词 word1 和 word2，找出将 word1 转换成 word2 所使用的最少的步骤数（每个操作记为一步）。",
          "slug": "给出两个单词-word1-和-word2-找出将-word1-转换成-word2-所使用的最少的步骤数-每个操作记为一步-。"
        },
        {
          "level": 2,
          "title": "性能优化",
          "slug": "性能优化"
        },
        {
          "level": 3,
          "title": "如何进行网站性能优化，请简述。",
          "slug": "如何进行网站性能优化-请简述。"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "Terminal下的一些配置",
      "frontmatter": {
        "title": "Terminal下的一些配置",
        "date": "2018-01-13T16:07:32.000Z",
        "tags": [
          "JavaScript",
          "git"
        ],
        "category": "git",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/Terminal/Terminal%E4%B8%8B%E7%9A%84%E4%B8%80%E4%BA%9B%E9%85%8D%E7%BD%AE.html",
      "relativePath": "posts/Terminal/Terminal下的一些配置.md",
      "key": "v-22e1ddf0",
      "path": "/2018/01/13/terminal%E4%B8%8B%E7%9A%84%E4%B8%80%E4%BA%9B%E9%85%8D%E7%BD%AE/",
      "headers": [
        {
          "level": 3,
          "title": "mac下使用homebrew",
          "slug": "mac下使用homebrew"
        },
        {
          "level": 3,
          "title": "安装完 Git 第一件事要配置自己的信息",
          "slug": "安装完-git-第一件事要配置自己的信息"
        },
        {
          "level": 3,
          "title": "连接远程仓库要配置自己的 ssh 秘钥",
          "slug": "连接远程仓库要配置自己的-ssh-秘钥"
        },
        {
          "level": 3,
          "title": "如果没有 SSH 私钥则需要创建一个私钥来放到 Github 上面使用",
          "slug": "如果没有-ssh-私钥则需要创建一个私钥来放到-github-上面使用"
        },
        {
          "level": 3,
          "title": "查看全局安装过的包",
          "slug": "查看全局安装过的包"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "解决使用git，ssh每次都要输入密码",
      "frontmatter": {
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/Terminal/%E8%A7%A3%E5%86%B3%E4%BD%BF%E7%94%A8git%EF%BC%8Cssh%E6%AF%8F%E6%AC%A1%E9%83%BD%E8%A6%81%E8%BE%93%E5%85%A5%E5%AF%86%E7%A0%81.html",
      "relativePath": "posts/Terminal/解决使用git，ssh每次都要输入密码.md",
      "key": "v-4f2dd40f",
      "path": "/1970/01/01/%E8%A7%A3%E5%86%B3%E4%BD%BF%E7%94%A8git-ssh%E6%AF%8F%E6%AC%A1%E9%83%BD%E8%A6%81%E8%BE%93%E5%85%A5%E5%AF%86%E7%A0%81/",
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "npm 与 yarn 管理工具",
      "frontmatter": {
        "title": "npm 与 yarn 管理工具",
        "tags": [
          "npm",
          "yarn"
        ],
        "category": [
          "npm"
        ],
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/Nodejs/npm%E4%B8%8Eyarn.html",
      "relativePath": "posts/Nodejs/npm与yarn.md",
      "key": "v-73ee917a",
      "path": "/1970/01/01/npm%E4%B8%8Eyarn/",
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "Axios 基础配置",
      "frontmatter": {
        "title": "Axios 基础配置",
        "date": "2018-01-13T16:07:32.000Z",
        "tags": [
          "Vue",
          "Axios"
        ],
        "category": "前端",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/Vue/Axios%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE.html",
      "relativePath": "posts/Vue/Axios基础配置.md",
      "key": "v-7ac8ca15",
      "path": "/2018/01/13/axios%E5%9F%BA%E7%A1%80%E9%85%8D%E7%BD%AE/",
      "headers": [
        {
          "level": 3,
          "title": "全局的 axios 默认值",
          "slug": "全局的-axios-默认值"
        },
        {
          "level": 3,
          "title": "自定义实例默认值",
          "slug": "自定义实例默认值"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "将Windows快捷键与MacOS同步",
      "frontmatter": {
        "title": "将Windows快捷键与MacOS同步",
        "tags": [
          "Windows",
          "MacOS"
        ],
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/Windows/autohotkey.html",
      "relativePath": "posts/Windows/autohotkey.md",
      "key": "v-8485141e",
      "path": "/1970/01/01/autohotkey/",
      "headers": [
        {
          "level": 3,
          "title": "autohotkey",
          "slug": "autohotkey"
        },
        {
          "level": 3,
          "title": "开机自启",
          "slug": "开机自启"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "vuepress主题配置",
      "frontmatter": {
        "title": "vuepress主题配置",
        "tags": [
          "vuepress",
          "markdown"
        ],
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/Vue/vuepress%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE.html",
      "relativePath": "posts/Vue/vuepress主题配置.md",
      "key": "v-441fe432",
      "path": "/1970/01/01/vuepress%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "快速上手",
          "slug": "快速上手"
        },
        {
          "level": 2,
          "title": "目录结构",
          "slug": "目录结构"
        },
        {
          "level": 2,
          "title": "主题配置",
          "slug": "主题配置"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "Css布局",
      "frontmatter": {
        "title": "Css布局",
        "tags": [
          "CSS"
        ],
        "category": "前端",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/Vue/layout.html",
      "relativePath": "posts/Vue/layout.md",
      "key": "v-301842a5",
      "path": "/1970/01/01/layout/",
      "headers": [
        {
          "level": 3,
          "title": "单栏布局",
          "slug": "单栏布局"
        },
        {
          "level": 3,
          "title": "两栏布局",
          "slug": "两栏布局"
        },
        {
          "level": 3,
          "title": "三栏布局",
          "slug": "三栏布局"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "leetcode初级算法",
      "frontmatter": {
        "title": "leetcode初级算法",
        "date": "2019-03-13T16:07:32.000Z",
        "tags": [
          "JavaScript",
          "算法",
          "LeetCode"
        ],
        "category": "算法",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/leetcode/LeetCode.html",
      "relativePath": "posts/leetcode/LeetCode.md",
      "key": "v-df6dc312",
      "path": "/2019/03/13/leetcode/",
      "headers": [
        {
          "level": 3,
          "title": "26.从排序数组中删除重复项",
          "slug": "_26-从排序数组中删除重复项"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "frontmatter in vuepress 1",
      "frontmatter": {
        "title": "frontmatter in vuepress 1",
        "date": "2018-11-7",
        "tags": [
          "frontmatter",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/test/2018-11-7-frontmatter-in-vuepress.html",
      "relativePath": "posts/test/2018-11-7-frontmatter-in-vuepress.md",
      "key": "v-13758977",
      "path": "/2018/11/07/frontmatter-in-vuepress/",
      "headers": [
        {
          "level": 2,
          "title": "Alternative Front Matter Formats",
          "slug": "alternative-front-matter-formats"
        },
        {
          "level": 2,
          "title": "Predefined Variables",
          "slug": "predefined-variables"
        },
        {
          "level": 3,
          "title": "title",
          "slug": "title"
        },
        {
          "level": 3,
          "title": "lang",
          "slug": "lang"
        },
        {
          "level": 3,
          "title": "description",
          "slug": "description"
        },
        {
          "level": 3,
          "title": "layout",
          "slug": "layout"
        },
        {
          "level": 3,
          "title": "permalink",
          "slug": "permalink"
        },
        {
          "level": 3,
          "title": "metaTitle",
          "slug": "metatitle"
        },
        {
          "level": 3,
          "title": "meta",
          "slug": "meta"
        },
        {
          "level": 2,
          "title": "Predefined Variables Powered By Default Theme",
          "slug": "predefined-variables-powered-by-default-theme"
        },
        {
          "level": 3,
          "title": "navbar",
          "slug": "navbar"
        },
        {
          "level": 3,
          "title": "sidebar",
          "slug": "sidebar"
        }
      ],
      "excerpt": "<p>Any markdown file that contains a YAML front matter block will be processed by <a href=\"https://github.com/jonschlinkert/gray-matter\" target=\"_blank\" rel=\"noopener noreferrer\">gray-matter<OutboundLink/></a>. The front matter must be the first thing in the markdown file and must take the form of valid YAML set between triple-dashed lines. Here is a basic example:</p>\n",
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "frontmatter in vuepress 2",
      "frontmatter": {
        "title": "frontmatter in vuepress 2",
        "date": "2018-11-7",
        "tags": [
          "frontmatter",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/test/2018-11-7-frontmatter-in-vuepress-2.html",
      "relativePath": "posts/test/2018-11-7-frontmatter-in-vuepress-2.md",
      "key": "v-3890e6a6",
      "path": "/2018/11/07/frontmatter-in-vuepress-2/",
      "headers": [
        {
          "level": 2,
          "title": "Alternative Front Matter Formats",
          "slug": "alternative-front-matter-formats"
        },
        {
          "level": 2,
          "title": "Predefined Variables",
          "slug": "predefined-variables"
        },
        {
          "level": 3,
          "title": "title",
          "slug": "title"
        },
        {
          "level": 3,
          "title": "lang",
          "slug": "lang"
        },
        {
          "level": 3,
          "title": "description",
          "slug": "description"
        },
        {
          "level": 3,
          "title": "layout",
          "slug": "layout"
        },
        {
          "level": 3,
          "title": "permalink",
          "slug": "permalink"
        },
        {
          "level": 3,
          "title": "metaTitle",
          "slug": "metatitle"
        },
        {
          "level": 3,
          "title": "meta",
          "slug": "meta"
        },
        {
          "level": 2,
          "title": "Predefined Variables Powered By Default Theme",
          "slug": "predefined-variables-powered-by-default-theme"
        },
        {
          "level": 3,
          "title": "navbar",
          "slug": "navbar"
        },
        {
          "level": 3,
          "title": "sidebar",
          "slug": "sidebar"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "Markdown Slot 2",
      "frontmatter": {
        "title": "Markdown Slot 2",
        "date": "2019-2-26",
        "tags": [
          "markdown",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/test/2019-2-26-markdown-slot-2.html",
      "relativePath": "posts/test/2019-2-26-markdown-slot-2.md",
      "key": "v-a0c5d8de",
      "path": "/2019/02/26/markdown-slot-2/",
      "headers": [
        {
          "level": 2,
          "title": "Why do I need Markdown Slot?",
          "slug": "why-do-i-need-markdown-slot"
        },
        {
          "level": 2,
          "title": "Named Slots",
          "slug": "named-slots"
        },
        {
          "level": 2,
          "title": "Default Slot Content",
          "slug": "default-slot-content"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "frontmatter in vuepress 3",
      "frontmatter": {
        "title": "frontmatter in vuepress 3",
        "date": "2018-11-7",
        "tags": [
          "frontmatter",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/test/2018-11-7-frontmatter-in-vuepress-3.html",
      "relativePath": "posts/test/2018-11-7-frontmatter-in-vuepress-3.md",
      "key": "v-32ba8faa",
      "path": "/2018/11/07/frontmatter-in-vuepress-3/",
      "headers": [
        {
          "level": 2,
          "title": "Alternative Front Matter Formats",
          "slug": "alternative-front-matter-formats"
        },
        {
          "level": 2,
          "title": "Predefined Variables",
          "slug": "predefined-variables"
        },
        {
          "level": 3,
          "title": "title",
          "slug": "title"
        },
        {
          "level": 3,
          "title": "lang",
          "slug": "lang"
        },
        {
          "level": 3,
          "title": "description",
          "slug": "description"
        },
        {
          "level": 3,
          "title": "layout",
          "slug": "layout"
        },
        {
          "level": 3,
          "title": "permalink",
          "slug": "permalink"
        },
        {
          "level": 3,
          "title": "metaTitle",
          "slug": "metatitle"
        },
        {
          "level": 3,
          "title": "meta",
          "slug": "meta"
        },
        {
          "level": 2,
          "title": "Predefined Variables Powered By Default Theme",
          "slug": "predefined-variables-powered-by-default-theme"
        },
        {
          "level": 3,
          "title": "navbar",
          "slug": "navbar"
        },
        {
          "level": 3,
          "title": "sidebar",
          "slug": "sidebar"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "Markdown Slot 3",
      "frontmatter": {
        "title": "Markdown Slot 3",
        "date": "2019-2-26",
        "tags": [
          "markdown",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/test/2019-2-26-markdown-slot-3.html",
      "relativePath": "posts/test/2019-2-26-markdown-slot-3.md",
      "key": "v-6ac979cf",
      "path": "/2019/02/26/markdown-slot-3/",
      "headers": [
        {
          "level": 2,
          "title": "Why do I need Markdown Slot?",
          "slug": "why-do-i-need-markdown-slot"
        },
        {
          "level": 2,
          "title": "Named Slots",
          "slug": "named-slots"
        },
        {
          "level": 2,
          "title": "Default Slot Content",
          "slug": "default-slot-content"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "Markdown Slot 4",
      "frontmatter": {
        "title": "Markdown Slot 4",
        "date": "2019-2-26",
        "tags": [
          "markdown",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/test/2019-2-26-markdown-slot-4.html",
      "relativePath": "posts/test/2019-2-26-markdown-slot-4.md",
      "key": "v-25f5e00d",
      "path": "/2019/02/26/markdown-slot-4/",
      "headers": [
        {
          "level": 2,
          "title": "Why do I need Markdown Slot?",
          "slug": "why-do-i-need-markdown-slot"
        },
        {
          "level": 2,
          "title": "Named Slots",
          "slug": "named-slots"
        },
        {
          "level": 2,
          "title": "Default Slot Content",
          "slug": "default-slot-content"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "Markdown Slot 1",
      "frontmatter": {
        "title": "Markdown Slot 1",
        "date": "2019-2-26",
        "tags": [
          "markdown",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Hangzhou",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/test/2019-2-26-markdown-slot.html",
      "relativePath": "posts/test/2019-2-26-markdown-slot.md",
      "key": "v-6f96281b",
      "path": "/2019/02/26/markdown-slot/",
      "headers": [
        {
          "level": 2,
          "title": "Why do I need Markdown Slot?",
          "slug": "why-do-i-need-markdown-slot"
        },
        {
          "level": 2,
          "title": "Named Slots",
          "slug": "named-slots"
        },
        {
          "level": 2,
          "title": "Default Slot Content",
          "slug": "default-slot-content"
        },
        {
          "level": 2,
          "title": "Example",
          "slug": "example"
        }
      ],
      "excerpt": "<p>VuePress implements a content distribution API for Markdown. With this feature, you can split your document into multiple fragments to facilitate flexible composition in the layout component.</p>\n",
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "原型连",
      "frontmatter": {
        "title": "原型连",
        "tags": [
          "js"
        ],
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/protype.html",
      "relativePath": "posts/protype.md",
      "key": "v-1c1e25b7",
      "path": "/1970/01/01/protype/",
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "writing a vuepress theme 3",
      "frontmatter": {
        "title": "writing a vuepress theme 3",
        "date": "2019-5-6",
        "tags": [
          "theme",
          "blog",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Shanghai",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/test/2019-5-6-writing-a-vuepress-theme-3.html",
      "relativePath": "posts/test/2019-5-6-writing-a-vuepress-theme-3.md",
      "key": "v-6c8dcfe1",
      "path": "/2019/05/06/writing-a-vuepress-theme-3/",
      "headers": [
        {
          "level": 2,
          "title": "Content Outlet",
          "slug": "content-outlet"
        },
        {
          "level": 2,
          "title": "Directory Structure",
          "slug": "directory-structure"
        },
        {
          "level": 2,
          "title": "Layout Component",
          "slug": "layout-component"
        },
        {
          "level": 2,
          "title": "Apply plugins",
          "slug": "apply-plugins"
        },
        {
          "level": 2,
          "title": "Site and Page Metadata",
          "slug": "site-and-page-metadata"
        },
        {
          "level": 2,
          "title": "App Level Enhancements",
          "slug": "app-level-enhancements"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "writing a vuepress theme 2",
      "frontmatter": {
        "title": "writing a vuepress theme 2",
        "date": "2019-5-6",
        "tags": [
          "theme",
          "blog",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Shanghai",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/test/2019-5-6-writing-a-vuepress-theme-2.html",
      "relativePath": "posts/test/2019-5-6-writing-a-vuepress-theme-2.md",
      "key": "v-69a2a463",
      "path": "/2019/05/06/writing-a-vuepress-theme-2/",
      "headers": [
        {
          "level": 2,
          "title": "Content Outlet",
          "slug": "content-outlet"
        },
        {
          "level": 2,
          "title": "Directory Structure",
          "slug": "directory-structure"
        },
        {
          "level": 2,
          "title": "Layout Component",
          "slug": "layout-component"
        },
        {
          "level": 2,
          "title": "Apply plugins",
          "slug": "apply-plugins"
        },
        {
          "level": 2,
          "title": "Site and Page Metadata",
          "slug": "site-and-page-metadata"
        },
        {
          "level": 2,
          "title": "App Level Enhancements",
          "slug": "app-level-enhancements"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "writing a vuepress theme 4",
      "frontmatter": {
        "title": "writing a vuepress theme 4",
        "date": "2019-5-6",
        "tags": [
          "theme",
          "blog",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Shanghai",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/test/2019-5-6-writing-a-vuepress-theme-4.html",
      "relativePath": "posts/test/2019-5-6-writing-a-vuepress-theme-4.md",
      "key": "v-6f78fb5f",
      "path": "/2019/05/06/writing-a-vuepress-theme-4/",
      "headers": [
        {
          "level": 2,
          "title": "Content Outlet",
          "slug": "content-outlet"
        },
        {
          "level": 2,
          "title": "Directory Structure",
          "slug": "directory-structure"
        },
        {
          "level": 2,
          "title": "Layout Component",
          "slug": "layout-component"
        },
        {
          "level": 2,
          "title": "Apply plugins",
          "slug": "apply-plugins"
        },
        {
          "level": 2,
          "title": "Site and Page Metadata",
          "slug": "site-and-page-metadata"
        },
        {
          "level": 2,
          "title": "App Level Enhancements",
          "slug": "app-level-enhancements"
        }
      ],
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "title": "Writing a vuepress theme 1",
      "frontmatter": {
        "title": "Writing a vuepress theme 1",
        "date": "2019-5-6",
        "tags": [
          "theme",
          "blog",
          "vuepress"
        ],
        "author": "ULIVZ",
        "location": "Shanghai",
        "layout": "Post",
        "permalink": "/:year/:month/:day/:slug"
      },
      "regularPath": "/posts/test/2019-5-6-writing-a-vuepress-theme.html",
      "relativePath": "posts/test/2019-5-6-writing-a-vuepress-theme.md",
      "key": "v-453ee96d",
      "path": "/2019/05/06/writing-a-vuepress-theme/",
      "headers": [
        {
          "level": 2,
          "title": "Content Outlet",
          "slug": "content-outlet"
        },
        {
          "level": 2,
          "title": "Directory Structure",
          "slug": "directory-structure"
        },
        {
          "level": 2,
          "title": "Layout Component",
          "slug": "layout-component"
        },
        {
          "level": 2,
          "title": "Apply plugins",
          "slug": "apply-plugins"
        },
        {
          "level": 2,
          "title": "Site and Page Metadata",
          "slug": "site-and-page-metadata"
        },
        {
          "level": 2,
          "title": "App Level Enhancements",
          "slug": "app-level-enhancements"
        }
      ],
      "excerpt": "<p>To write a theme, create a <code>.vuepress/theme</code> directory in your docs root, and then create a <code>Layout.vue</code> file:</p>\n<!--beforebegin--><div class=\"language- extra-class\"><!--afterbegin--><pre v-pre class=\"language-text\"><code>.\n└─ .vuepress\n   └─ `theme`\n       └─ Layout.vue\n</code></pre>\n<!--beforeend--></div><!--afterend--><p>From there it's the same as developing a normal Vue application. It is entirely up to you how to organize your theme.</p>\n",
      "id": "post",
      "pid": "post",
      "lastUpdated": "2022-01-20 16:09:35",
      "lastUpdatedTimestamp": 1642666175000
    },
    {
      "frontmatter": {
        "layout": "List",
        "title": "Post"
      },
      "regularPath": "/list/",
      "key": "v-42d9971c",
      "path": "/list/"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "Timeline",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "ngxin Tags"
      },
      "regularPath": "/tag/ngxin/",
      "key": "v-6d753ed6",
      "path": "/tag/ngxin/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "Mac Tags"
      },
      "regularPath": "/tag/Mac/",
      "key": "v-325022ec",
      "path": "/tag/Mac/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "Koa Tags"
      },
      "regularPath": "/tag/Koa/",
      "key": "v-32518bc8",
      "path": "/tag/Koa/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "Sequelize Tags"
      },
      "regularPath": "/tag/Sequelize/",
      "key": "v-c955477c",
      "path": "/tag/Sequelize/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "JavaScript Tags"
      },
      "regularPath": "/tag/JavaScript/",
      "key": "v-7a5f6990",
      "path": "/tag/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "面试题 Tags"
      },
      "regularPath": "/tag/%E9%9D%A2%E8%AF%95%E9%A2%98/",
      "key": "v-19493022",
      "path": "/tag/面试题/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "git Tags"
      },
      "regularPath": "/tag/git/",
      "key": "v-32383f72",
      "path": "/tag/git/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "npm Tags"
      },
      "regularPath": "/tag/npm/",
      "key": "v-3231af64",
      "path": "/tag/npm/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "yarn Tags"
      },
      "regularPath": "/tag/yarn/",
      "key": "v-12dba5fe",
      "path": "/tag/yarn/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "Vue Tags"
      },
      "regularPath": "/tag/Vue/",
      "key": "v-32475d9a",
      "path": "/tag/Vue/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "Axios Tags"
      },
      "regularPath": "/tag/Axios/",
      "key": "v-7d6421c3",
      "path": "/tag/Axios/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "Windows Tags"
      },
      "regularPath": "/tag/Windows/",
      "key": "v-dea8ba54",
      "path": "/tag/Windows/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "MacOS Tags"
      },
      "regularPath": "/tag/MacOS/",
      "key": "v-ded21334",
      "path": "/tag/MacOS/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "vuepress Tags"
      },
      "regularPath": "/tag/vuepress/",
      "key": "v-dfb71430",
      "path": "/tag/vuepress/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "markdown Tags"
      },
      "regularPath": "/tag/markdown/",
      "key": "v-3ae5b494",
      "path": "/tag/markdown/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "CSS Tags"
      },
      "regularPath": "/tag/CSS/",
      "key": "v-3259a754",
      "path": "/tag/CSS/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "算法 Tags"
      },
      "regularPath": "/tag/%E7%AE%97%E6%B3%95/",
      "key": "v-89abd2d6",
      "path": "/tag/算法/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "LeetCode Tags"
      },
      "regularPath": "/tag/LeetCode/",
      "key": "v-79ce5560",
      "path": "/tag/LeetCode/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "frontmatter Tags"
      },
      "regularPath": "/tag/frontmatter/",
      "key": "v-f8241222",
      "path": "/tag/frontmatter/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "js Tags"
      },
      "regularPath": "/tag/js/",
      "key": "v-e8d86dc8",
      "path": "/tag/js/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "theme Tags"
      },
      "regularPath": "/tag/theme/",
      "key": "v-58f012a0",
      "path": "/tag/theme/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterPagination",
        "title": "blog Tags"
      },
      "regularPath": "/tag/blog/",
      "key": "v-1559f73a",
      "path": "/tag/blog/"
    },
    {
      "frontmatter": {
        "layout": "Layout",
        "title": "Page 2 | Post"
      },
      "regularPath": "/list/page/2/",
      "key": "v-f58cf1be",
      "path": "/list/page/2/"
    }
  ],
  "themeConfig": {
    "footer": {
      "contact": "联系",
      "links": [
        {
          "text": "GitHub",
          "link": "github.com"
        },
        {
          "text": "Twitter",
          "link": "github.com"
        }
      ]
    },
    "home": {
      "background": {
        "show": false,
        "fileName": "/bg.png"
      }
    },
    "darkMode": {
      "switch": true,
      "auto": false,
      "on": "18:00",
      "off": "06:00"
    },
    "comment": {
      "service": "disqus",
      "shortname": "1net-1"
    },
    "nav": [
      {
        "text": "文档",
        "link": "/list/"
      },
      {
        "text": "标签",
        "link": "/tag/"
      },
      {
        "text": "Github",
        "link": "https://github.com/sogud"
      }
    ],
    "summary": true,
    "summaryLength": 200,
    "pwa": false
  }
}