# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: https://registry.npmjs.org/ 
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  deploy:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [14.x]
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
            registry-url: https://registry.npmjs.org/ 
        # Runs a single command using the runners shell
        - name: Install
          run: npm install yarn -g && yarn install

        # Runs a set of commands using the runners shell
        - name: Build
          run: npm run example:build
